In [1]:
import logging

logging.disable(logging.INFO)  # desabilita INFO temporariamente

#logging.disable(logging.NOTSET)  # reativa se quiser depois

In [6]:
from buscaEndereco_CET_v12_0 import (
    buscar_endereco_com_coordenadas,   # ← Nova: substitui buscar_endereco_candidatos
    buscar_endereco_completo,          # ← Nova: substitui buscar_endereco_enriquecido.
    enriquecer_candidatos_geoserver    # ← Nova: enriquecimento separado
)

In [3]:
!pip install requests pandas openpyxl geopandas shapely unidecode

Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: pandas in C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.3)
Requirement already satisfied: openpyxl in C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Collecting geopandas
  Using cached geopandas-1.1.4-py3-none-any.whl.metadata (2.3 kB)
Collecting shapely
  Using cached shapely-2.1.2-cp314-cp314-win_amd64.whl.metadata (7.1 kB)
Collecting unidecode
  Using cached Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (3.4.7)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)
Collecting pyogrio>=0.7.2 (from geopandas)
  Using cached pyogrio-0.13.0-cp311-abi3-win_amd64.whl.metadata (6.0 kB)
Requirement already satisfied: packaging in C:\Users\davi.faria\AppData\Roaming\Python\Python314\site-packages (from geopandas) (26.3)
Collecting pyproj>=3.5.0 (from geopandas)
  Using cached pyproj-3.7.2-cp314-cp314-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: six>=1.5 in C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached geopandas-1.1.4-py3-none-any.whl (343 kB)
Using cached shapely-2.1.2-cp314-cp314-win_amd64.whl (1.8 MB)
Using cached Unidecode-1.4.0-py3-none-any.whl (235 kB)
Using cached certifi-2026.7.22-py3-none-any.whl (136 kB)
Using cached pyogrio-0.13.0-cp311-abi3-win_amd64.whl (23.8 MB)
Using cached pyproj-3.7.2-cp314-cp314-win_amd64.whl (6.4 MB)
Installing collected packages: urllib3, unidecode, shapely, idna, certifi, requests, pyproj, pyogrio, geopandas

   ---------------------------------------- 0/9 [urllib3]
   ---------------------------------------- 0/9 [urllib3]
   ---------------------------------------- 0/9 [urllib3]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   ---- ----------------------------------- 1/9 [unidecode]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   -------- ------------------------------- 2/9 [shapely]
   ------------- -------------------------- 3/9 [idna]
   ------------- -------------------------- 3/9 [idna]
   ------------- -------------------------- 3/9 [idna]
   ------------- -------------------------- 3/9 [idna]
   ------------- -------------------------- 3/9 [idna]
   ----------------- ---------------------- 4/9 [certifi]
   ----------------- ---------------------- 4/9 [certifi]
   ---------------------- ----------------- 5/9 [requests]
   ---------------------- ----------------- 5/9 [requests]
   ---------------------- ----------------- 5/9 [requests]
   -------------------------- ------------- 6/9 [pyproj]
   -------------------------- ------------- 6/9 [pyproj]
   -------------------------- ------------- 6/9 [pyproj]
   -------------------------- ------------- 6/9 [pyproj]
   -------------------------- ------------- 6/9 [pyproj]
   -------------------------- ------------- 6/9 [pyproj]
   -------------------------- ------------- 6/9 [pyproj]
   -------------------------- ------------- 6/9 [pyproj]
   -------------------------- ------------- 6/9 [pyproj]
   -------------------------- ------------- 6/9 [pyproj]
   -------------------------- ------------- 6/9 [pyproj]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ------------------------------- -------- 7/9 [pyogrio]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ----------------------------------- ---- 8/9 [geopandas]
   ---------------------------------------- 9/9 [geopandas]

Successfully installed certifi-2026.7.22 geopandas-1.1.4 idna-3.18 pyogrio-0.13.0 pyproj-3.7.2 requests-2.34.2 shapely-2.1.2 unidecode-1.4.0 urllib3-2.7.0

  WARNING: The script unidecode.exe is installed in 'C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script idna.exe is installed in 'C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pyproj.exe is installed in 'C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
!pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\davi.faria\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.24.0-py3-none-any.whl (461 kB)
Using cached scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn

   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
buscar_endereco_completo('RUA DOUTOR LUIS AIRES',1364,-23.5375,-46.487).head(25)

,codlog,logradouro_PMSP,latitude_geocode,longitude_geocode,distancia_km,similaridade,_fonte_busca,GET,DET,SUB,Distrito_Nome,Regiao_Nome,Classificacao
1,12156,R DR LUIZ AYRES,-23.536678,-46.487286,0.096,100.0,EMBEDDING,LE,LE3,PE,ARTUR ALVIM,Leste,ARTERIAL
2,02633,R DOS AIRES,-23.595366,-46.541067,8.472,64.0,EMBEDDING,SE,SE1,VP,SAO LUCAS,Leste,LOCAL
3,15711,R DR PAULO AIRES NETO,-23.654265,-46.680679,23.623,63.0,EMBEDDING,SU,SU3,SA,CAMPO GRANDE,Sul,LOCAL
4,11115,R DR JOSE AIRES NETO,-23.580949,-46.735792,25.815,67.0,EMBEDDING,OE,OE2,BT,BUTANTA,Oeste,LOCAL
5,02646,R DR AIRES MARTINS TORRES,-23.558640,-46.760382,27.966,64.0,EMBEDDING,OE,OE2,BT,RIO PEQUENO,Oeste,COLETORA

In [ ]:
buscar_endereco_completo('RUA DOUTOR LUIS AIRES',100,-23.5322045,-46.5007899).head(25)

In [ ]:
buscar_endereco_completo('RUA EDISON',640,-23.6215138,-46.6766455).head(25)

In [ ]:
buscar_endereco_completo('SPEERS',738,-23.5181108,-46.701804).head(25)

In [ ]:
# Teste 1 - Verificar se a função está sendo chamada
#result1 
buscar_endereco_com_coordenadas('SP 070', '15', -23.5, -46.6)

In [ ]:
# Teste 2 - Verificar com número explícito
#result2
buscar_endereco_com_coordenadas('SP 070', '5', -23.5, -46.6)

In [2]:
buscar_endereco_completo('RUA ORIENTE',749,-23.5376434,-46.6148791).head(25)

2026-01-07 14:37:50,950 - INFO - 🔍 Buscando: 'RUA ORIENTE', Número: '749'
2026-01-07 14:37:50,996 - INFO - ✅ 1 resultado(s) EXATO(s) relevantes
2026-01-07 14:37:51,269 - INFO - ✅ Resultado principal considerado SUFICIENTE

,codlog,logradouro_PMSP,latitude_geocode,longitude_geocode,distancia_km,similaridade,_fonte_busca,GET,DET,SUB,Distrito_Nome,Regiao_Nome,Classificacao
0,15053,R ORIENTE,-23.538037,-46.621307,0.657,100,EXATO,LE,LE1,MO,BRAS,Leste,COLETORA

In [8]:
buscar_endereco_com_coordenadas('TUNEL 9 DE JULHO',	100,	-23.5623415,	-46.6561352).head(25)

2026-08-12 09:34:26,194 - WARNING - ❌ GEOCODE falhou após 3 tentativas para 'TUNEL NOVE DE JULHO, 100': 500 Server Error: Internal Server Error for url: http://cetaplica/geosoap/geocode.asmx/buscaEnderecos?endereco=TUNEL+NOVE+DE+JULHO%2C+100

,codlog,logradouro_PMSP,latitude_geocode,longitude_geocode,distancia_km,similaridade,_fonte_busca
1,48365,TN DAHER ELIAS CUTAIT,-23.561363,-46.655750,0.116,100.0,EMBEDDING
2,14810,VD NOVE DE JULHO,-23.548915,-46.642384,2.048,63.0,EMBEDDING
3,14804,AV NOVE DE JULHO,-23.548878,-46.639911,2.231,69.0,EMBEDDING
4,14806,R NOVE DE JULHO,-23.644345,-46.700333,10.170,80.0,EMBEDDING
5,51955,PC JARDIM NOVE DE JULHO,-23.590600,-46.483237,17.899,60.0,EMBEDDING
6,50241,PQ NOVE DE JULHO,-23.720791,-46.708871,18.420,66.0,EMBEDDING
7,Z5155,R NOVE DE JULHO (GRAJAU),-23.762502,-46.686402,22.469,80.0,EMBEDDING
8,Z5272,R VINTE E NOVE DE JULHO (JD HELENA),-23.483469,-46.415751,26.030,67.0,EMBEDDING

In [9]:
buscar_endereco_com_coordenadas('RUA 24 DE MAIO',	166,	-23.5438105,	-46.6398333).head(25)

,codlog,logradouro_PMSP,latitude_geocode,longitude_geocode,distancia_km,similaridade,_fonte_busca
0,19759,R VINTE E QUATRO DE MAIO,-23.544042,-46.639877,0.026,100,EXATO

In [ ]:
buscar_endereco_com_coordenadas('JACEGUAVA',	863,	-23.77082474,	-46.73260551).head(25)

In [ ]:
buscar_endereco_com_coordenadas('DO JACEGUAVA',	863,	-23.77082474,	-46.73260551).head(25)

In [ ]:
buscar_endereco_com_coordenadas('AVENIDA DO JACEGUAVA',	863,	-23.77082474,	-46.73260551).head(25)

In [ ]:
buscar_endereco_com_coordenadas('SP 021',103,-23.8039357,-46.7051759).head(25)

In [ ]:
buscar_endereco_com_coordenadas('SP 021',99,-23.8039357,-46.7051759).head(25)

In [ ]:
buscar_endereco_com_coordenadas('SP 270',12,-23.5571019,-46.6701834).head(25)

In [ ]:
buscar_endereco_com_coordenadas('AVENIDA 23 DE MAIO',11,-23.5691774,-46.64089).head(25)

In [ ]:
buscar_endereco_com_coordenadas('AVENIDA 23 DE MAIO',11000,-23.5691774,-46.64089).head(25)
#não melhoria considerar Km

In [ ]:
buscar_endereco_completo('SP 070',	15,	-23.49652885,	-46.52947422).head(25)

In [ ]:
buscar_endereco_completo('SP 070',	15,	-23.49652885,	-46.52947422).head(25)

In [ ]:
buscar_endereco_completo('ayrton senna',	15000,	-23.49652885,	-46.52947422).head(25)

In [ ]:
buscar_endereco_completo('R PINHEIRO DE LEMOS',28,-23.600861,-46.595778).head(25)

In [ ]:
buscar_endereco_completo('RUA DAS JUNTAS PROVISORIAS',280,-23.5894924,-46.5984088).head(25)

In [ ]:
buscar_endereco_com_coordenadas('DE ITAPECERICA',3421,-23.65627152,-46.76275546).head(25)

In [ ]:
buscar_endereco_com_coordenadas('R. DR ASSIS RIBEIRO',9590,-23.48280242,-46.47076485).head(25)

In [ ]:
buscar_endereco_com_coordenadas('AV DR ASSIS RIBEIRO',9590,-23.48280242,-46.47076485).head(25)

In [ ]:
buscar_endereco_com_coordenadas('ESTR LAZARO AMANCIO DE BARROS',284,-23.4669,-46.6947).head(25)

In [ ]:
buscar_endereco_com_coordenadas('avenida LAZARO AMANCIO DE BARROS',284,-23.4669,-46.6947).head(25)

In [ ]:
buscar_endereco_completo('SPEERS',1380,-23.5678529,-46.4581226).head(25)

In [ ]:
buscar_endereco_completo('RUA WILLIAM SPEERS',738,-23.5181108,-46.701804).head(25)

In [ ]:
buscar_endereco_completo('PONTE DA VILA MARIA',1,-23.5264292,-46.5961179).head(25)

In [ ]:
buscar_endereco_completo('RUA ROMA',15,-23.5227,-46.6976).head(25)

In [10]:
buscar_endereco_completo("ACESSO AVENIDA RADIAL LESTE OESTE",	100,	-23.55652418,	-46.63636798).head(25)

,codlog,logradouro_PMSP,latitude_geocode,longitude_geocode,distancia_km,similaridade,_fonte_busca,GET,DET,SUB,Distrito_Nome,Regiao_Nome,Classificacao
1,33987,AC A AV RADIAL LESTE OESTE,-23.556550,-46.636770,0.041,99.0,EMBEDDING,CN,SU1,SE,SE,Centro,COLETORA
2,33306,VD LESTE-OESTE,-23.556558,-46.632027,0.442,60.0,EMBEDDING,CN,CN3,SE,SE,Centro,VTR
3,00543,AV ALCANTARA MACHADO,-23.552003,-46.624116,1.346,81.0,EMBEDDING,LE,LE1,MO,BRAS,Leste,ARTERIAL
4,33667,AV RADIAL LESTE-OESTE,-23.548178,-46.647216,1.444,92.0,EMBEDDING,CN,CN3,SE,REPUBLICA,Centro,VTR
5,42308,AC A AV RADIAL LESTE OESTE,-23.547847,-46.647610,1.498,99.0,EMBEDDING,OE,CN3,SE,REPUBLICA,Centro,LOCAL
6,00544,VD ALCANTARA MACHADO,-23.552652,-46.617955,1.926,81.0,EMBEDDING,LE,LE1,MO,BRAS,Leste,ARTERIAL
7,35652,VD PIRES DO RIO - HERMES F FIGUEIREDO,-23.542136,-46.581028,5.864,81.0,EMBEDDING,LE,LE1,MO,BELEM,Leste,ARTERIAL
8,34122,R MELO FREIRE,-23.541046,-46.578027,6.191,81.0,EMBEDDING,LE,LE1,MO,TATUAPE,Leste,ARTERIAL
9,07645,AV CD DE FRONTIN,-23.536818,-46.557186,8.364,81.0,EMBEDDING,LE,LE1,AF,TATUAPE,Leste,ARTERIAL
10,01702,AV ANTONIO ESTEVAO DE CARVALHO,-23.531711,-46.521771,12.003,81.0,EMBEDDING,LE,LE3,PE,VILA MATILDE,Leste,ARTERIAL
11,53024,PC FRANCISCO SOTO - CHICAO,-23.531798,-46.501474,14.023,81.0,EMBEDDING,LE,LE3,PE,VILA MATILDE,Leste,COLETORA
12,12156,R DR LUIZ AYRES,-23.532120,-46.500613,14.102,81.0,EMBEDDING,LE,LE3,PE,ARTUR ALVIM,Leste,ARTERIAL
13,Z1615,TN AGUIA DE HAIA,-23.539803,-46.484798,15.562,81.0,EMBEDDING,LE,LE3,PE,ARTUR ALVIM,Leste,ARTERIAL
14,49302,R ENG SIDNEY APARECIDO DE MORAES,-23.540117,-46.472574,16.796,81.0,EMBEDDING,LE,LE4,IQ,ITAQUERA,Leste,COLETORA
15,49216,AV S.C. CORINTHIANS PAULISTA,-23.543349,-46.471307,16.889,81.0,EMBEDDING,LE,LE4,IQ,ITAQUERA,Leste,ARTERIAL
16,39641,TN JORN ODON PEREIRA,-23.542488,-46.466534,17.382,81.0,EMBEDDING,LE,LE4,IQ,ITAQUERA,Leste,ARTERIAL
17,22555,AV JOSE PINHEIRO BORGES,-23.540821,-46.465007,17.555,81.0,EMBEDDING,LE,LE4,IQ,ITAQUERA,Leste,ARTERIAL

In [ ]:
buscar_endereco_completo("TRABALHADORES",	100,	-23.55652418,	-46.63636798).head(25)

In [ ]:
buscar_endereco_completo('COMPLEXO VIARIO AYRTON SENNA',100,-23.5874,-46.665).head(25)

In [ ]:
buscar_endereco_completo('AYRTON SENNA',726,-23.506833,-46.550722).head(25)

In [ ]:
buscar_endereco_completo('AYRTON SENNA',26,-23.5067867,-46.5453531).head(25)

In [11]:
buscar_endereco_completo('RUA BAHIA',128,-23.5441643,-46.6596565).head(25)

,codlog,logradouro_PMSP,latitude_geocode,longitude_geocode,distancia_km,similaridade,_fonte_busca,GET,DET,SUB,Distrito_Nome,Regiao_Nome,Classificacao
0,02722,R BAHIA,-23.544137,-46.659527,0.014,100,EXATO,OE,OE1,SE,CONSOLACAO,Centro,COLETORA
1,Z4716,R BAHIA (JD MARIA RITA),-23.716105,-46.677667,19.207,100,EXATO,SU,SU3,CS,CID DUTRA,Sul,LOCAL
2,Z4363,R BAHIA (JD PAINEIRAS),-23.435146,-46.810684,19.600,100,EXATO,NO,NO3,PR,ANHANGUERA,Norte,LOCAL
3,Z1840,R BAHIA,-23.742041,-46.657493,22.004,100,EXATO,SU,SU4,CS,GRAJAU,Sul,LOCAL
4,Z4765,R BAHIA (JD PANTANAL),-23.480449,-46.409667,26.456,100,EXATO,LE,LE2,MP,JD HELENA,Leste,LOCAL
5,Z4890,R BAHIA (CID TIRADENTES),-23.587588,-46.397236,27.179,100,EXATO,LE,LE4,CT,CID TIRADENTES,Leste,LOCAL
6,Z1320,R BAHIA (JD VITORIA),-23.590003,-46.387876,28.165,100,EXATO,LE,LE4,CT,CID TIRADENTES,Leste,LOCAL
7,Z3620,R BAHIA,-23.791563,-46.723416,28.266,100,EXATO,SU,SU4,PA,PARELHEIROS,Sul,LOCAL

In [ ]:
buscar_endereco_completo('ANHANGUERA',4.899,-23.4343,-46.7864).head(25)

In [ ]:
buscar_endereco_completo('ANHANGUERA',5,-23.4343,-46.7864).head(25)

In [13]:
buscar_endereco_completo('TERMINAL METRO TATUAPE  SUL',10,-23.5412,-46.5767).head(25)

  logradouro_PMSP
0  NAO ENCONTRADO

In [ ]:
buscar_endereco_completo('RUA DO GASOMETRO',739,-23.5434,-46.6193).head(25)

In [14]:
buscar_endereco_completo('METRO PEDRO II',100,-23.5496652,-46.6258742).head(25)

  logradouro_PMSP
0  NAO ENCONTRADO

In [15]:
buscar_endereco_completo('ESTACAO CARRAO',1,-23.5378,-46.5641).head(25)

  logradouro_PMSP
0  NAO ENCONTRADO

In [16]:
buscar_endereco_completo('TERMINAL METRO TATUAPE  SUL',10,-23.5412,-46.5767).head(25)

  logradouro_PMSP
0  NAO ENCONTRADO

In [17]:
buscar_endereco_completo('METRO CONCEICAO',100,-23.635197,-46.6412687).head(25)

  logradouro_PMSP
0  NAO ENCONTRADO

In [18]:
buscar_endereco_completo('TERMINAL METRO CARRAO SUL',10,-23.5383501,-46.5634522).head(25)

  logradouro_PMSP
0  NAO ENCONTRADO

In [19]:
buscar_endereco_completo('ESTAÇÃO METRO CAMPO LIMPO',143,-23.64984785,-46.75936179).head(25)

  logradouro_PMSP
0  NAO ENCONTRADO

In [ ]:
buscar_endereco_completo('RUA BAHIA',300,-23.5457,-46.66).head(25)

In [ ]:
buscar_endereco_completo('PONTE DA FREGUESIA DO O',100,-23.5095,-46.6897).head(25)

In [ ]:
buscar_endereco_completo('RUA CORONEL GUILHERME ROCHA',290,-23.5209563,-46.5832167).head(25)

In [ ]:
buscar_endereco_completo('PONTE DO SOCORRO',10,-23.6649147,-46.7102462).head(25)

In [ ]:
buscar_endereco_completo('PTE SANTO DIAS DA SILVA',10,-23.6649147,-46.7102462).head(25)